name: run test.py

on:
  push:
    branches:
      - bus_ticket  # Modify the branch name as needed

jobs:
  trigger_jenkins:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Jenkins
        env:
          JENKINS_JOB_URL: 'http://localhost:8080/job/demo2/'
          JENKINS_API_TOKEN: '1165882fd521cb0b773c1e5f538e441948'
        run: |
          curl -X POST -u Shivam_Verma:$JENKINS_API_TOKEN $JENKINS_JOB_URL
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install cnvrgv2
          pip install -r requirements.txt

      - name: execute py script # run main.py
        run: pytest test.py
        
